services:
    rinsrans.selfdelete.listener:
        class: rinsrans\selfdelete\event\listener
        arguments:
            - @auth
            - @request
            - @user
        tags:
            - { name: event.listener }